### ISSUE TITLE
carrosel da pagina inicial

### ISSUE THREAD

**Issue by Famorelli** [Stramp/siteFabio#337]
Rafa, o carrossel vai ser baseado no do leandro twin...com  os textos chegando e as fotos selecionadas de fundo. se liga ai:

https://www.leandrotwin.com.br/site/

vou te passar texto:

1. Mais de 12 anos em Assessoria Fitness

2. Método baseado nas suas características individuais e estilo de vida.
Com ampla base científica

3. Mais de 500 casos de sucesso!
Venha conhecer a metodologia!

4. Satisfação garantida
ou seu dinheiro de volta
consulte condições.

5. Atendimento online e Presencial!

**Comment by Stramp** [comment]
@Famorelli ta falntando as imagens man !

**Comment by Famorelli** [comment]
> @Famorelli
> 
> **ta faltando as imagens man !**
> =D

coloque imagens neutras, como tem feito...mas acerta o texto.... logo te envio fotos profisisonais! mas faz andas ai o projeto man, por favor!

**Comment by Famorelli** [comment]
blz Rafa! vou escolher as fotos.
Lembrando que é um carrossel da sessão página inicial,  com a foto e a parte escrita . O modelo que eu vi foi do leandro twin 
https://www.leandrotwin.com.br/site/

1. Mais de 12 anos em Assessoria Fitness
foto:
![Captura de tela 2021-03-16 213412](https://user-images.githubusercontent.com/78149085/124521820-4cb39500-ddc7-11eb-8a8d-6c0bcb6bd572.png)


2. Método baseado na ciência, considerando suas características individuais e estilo de vida.

![Captura de tela 2021-03-16 212608](https://user-images.githubusercontent.com/78149085/124521730-fd6d6480-ddc6-11eb-9ea6-9eb464bb60a3.png)


3. Mais de 500 casos de sucesso!
Venha conhecer a metodologia!

![Captura de tela 2021-03-16 213826](https://user-images.githubusercontent.com/78149085/124521904-943a2100-ddc7-11eb-8d8f-f81b8afa00a9.png)


4. Satisfação garantida
ou seu dinheiro de volta
consulte condições.

![Captura de tela 2021-03-16 211950](https://user-images.githubusercontent.com/78149085/124521751-0bbb8080-ddc7-11eb-9386-8ab9697d5665.png)

5. Atendimento Online e Presencial!

![Captura de tela 2021-03-16 213206](https://user-images.githubusercontent.com/78149085/124521875-7cfb3380-ddc7-11eb-90ea-038cff554047.png)
